HealthApps/urls.py
"""
file: urls.py
description: urls with regex patterns for healthnet
"""

from django.conf.urls import url
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from .views.transfer import UpdateTransfer
from .views.blockOff import CreateBlockOff, UpdateBlockOff
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^createPatient', CreatePatient.as_view(), name='createPatient'),
    url(r'^index.html$', index, name='index'),
    # can view all of the appointments
    url(r'^appList$', app_list, name='appList'),
    # can create new appointment here
    url(r'^createAppointment$', CreateAppointment.as_view(), name='createAppointment'),
    # can update appointment with given id number
    url(r'^updateAppointment/(?P<pk>[0-9]+)/$', UpdateAppointment.as_view(), name='updateAppointment'),
    url(r'^cancelAppointment/(?P<pk>[0-9]+)/$', DeleteAppointment.as_view(), name='cancelAppointment'),
    # user auth urls
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^calView$', cal_view, name='calView'),

    url(r'^logTable', log_table, name='logTable'),
    url(r'^logItem/(?P<pk>[0-9]+)/$', view_log_item, name='logItem'),
    url(r'^patientList$', patient_list, name='patientList'),
    url(r'^transferPatientList$', transfer_patient_list, name='transferPatientList'),
    url(r'^createPrescription/(?P<pk>[0-9]+)/$', CreatePrescription.as_view(), name='createPrescription'),
    url(r'^createTest/(?P<pk>[0-9]+)/$', CreateTest.as_view(), name='createTest'),
    url(r'^createCustomEntry/(?P<pk>[0-9]+)/$', CreateCustomEntry.as_view(), name='createEMREntry'),
    url(r'^editVitals/(?P<pk>[0-9]+)/$', UpdateVitals.as_view(), name='editVitals'),
    url(r'^getPrescription/(?P<pk>[0-9]+)/$', get_prescription, name='getPrescription'),
    url(r'^getTest/(?P<pk>[0-9]+)/$', get_test, name='getTest'),

    url(r'^EMR/(?P<pk>[0-9]+)/$', emr, name='emr'),
    url(r'^toEMR/(?P<pk>[0-9]+)/$', to_emr, name='toEMR'),
    url(r'^emrEntry/(?P<pk>[0-9]+)$', emr_entry, name='emrEntry'),

    url(r'^delete/(?P<pk>[0-9]+)/$', delete_prescription, name='deletePrescription'),
    url(r'^release/(?P<pk>[0-9]+)/$', release_test, name='releaseResult'),
    url(r'^approveDoc/(?P<pk>[0-9]+)/$', approve_doc, name='approveDoc'),
    url(r'^approveNur/(?P<pk>[0-9]+)/$', approve_nur, name='approveNur'),
    url(r'^hide/(?P<pk>[0-9]+)/$', hide_entry, name='hideEntry'),
    url(r'^show/(?P<pk>[0-9]+)/$', show_entry, name='showEntry'),
    url(r'^admit/(?P<pk>[0-9]+)/$', admit_patient, name='admit'),
    url(r'^discharge/(?P<pk>[0-9]+)/$', discharge_patient, name='discharge'),
    url(r'^exportVitalsEntries/(?P<pk>[0-9]+)/$', export_vitals_entries, name='discharge'),

    url(r'^statistics$', form_handle, name='statistics'),

    url(r'^profile', profile, name='profile'),
    url(r'^updateProfile/(?P<pk>\d+)/', UpdateProfile.as_view(), name='updateProfile'),
    url(r'^updateUser/(?P<pk>[0-9]+)/$', UpdateUser.as_view(), name='updateUser'),
    url(r'^createHospital', CreateHospital.as_view(), name='createHospital'),
    url(r'^createDoctor', CreateDoctor.as_view(), name='createDoctor'),
    url(r'^createNurse', CreateNurse.as_view(), name='createNurse'),
    url(r'^createAdmin', CreateHospitalAdmin.as_view(), name='createAdmin'),
    url(r'^registerOptions$', registration_options, name='registerOptions'),
    url(r'^blockOff$', CreateBlockOff.as_view(), name='blockOff'),
    url(r'^updateBlockOff/(?P<pk>[0-9]+)/$', UpdateBlockOff.as_view(), name='updateTransfer'),
    url(r'^updateTransfer/(?P<pk>[0-9]+)/$', UpdateTransfer.as_view(), name='updateTransfer'),
    url(r'^approveList$', staffView, name='approveStaff'),
    url(r'^cascade_select/hospital-to-doctor/$', hospital_to_doctor, name='hospitalToDoctor'),
    url(r'^handleCSV$', handle_csv, name='handleCSV'),
    url(r'^exportCSV/(?P<string>[\w\-\.]+)/$', export_csv, name='exportCSV'),
    url(r'^importCSV/(?P<string>[\w\-\.]+)/$', import_csv, name='importCSV'),
]

HealthNet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include('django_messages.urls')),
    url(r'', include('HealthApps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthApps/models/Appointment.py
"""
file: Appointment.py
description: models for Appointments
"""

from django.db import models
import datetime
import time


class Appointment(models.Model):
    """
    Appointment model
    """
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    description = models.CharField(max_length=500, null=True)
    hospital = models.ForeignKey('HealthApps.Hospital', on_delete=models.DO_NOTHING)
    doctor = models.ForeignKey('HealthApps.Doctor', on_delete=models.DO_NOTHING)
    patient = models.ForeignKey('HealthApps.Patient', on_delete=models.DO_NOTHING, null = True)

    def __str__(self):
        """
        Tostring for Appointment
        :return: appointment description
        """
        if self.patient != None:
            return "Appointment with Dr." + self.doctor.user.last_name + " and " + self.patient.user.first_name + " " + self.patient.user.last_name
        else:
            return "Appointment with Dr." + self.doctor.user.last_name

    def conflict_checker(self, hospital, date, start_time, end_time, old_appointment):
        """
        Determines whether there is a scheduling conflict
        :param hospital: specific hospital
        :param date: specific date
        :param start_time: specific starting time
        :param end_time: specific ending time
        :param old_appointment: old appointment
        :return: whether or not it conflicts
        """
        doctor = self
        result = [True, "no message"]
        if datetime.datetime.combine(date, start_time) < datetime.datetime.now():
            result[0] = False
            result[1] = "Sorry, you cannot create appointments set in the past. Please try again."
        elif (datetime.datetime(100,1,1,start_time.hour, start_time.minute,00) + datetime.timedelta(minutes=30)).time() > end_time:
            result[0] = False
            result[1] = "Sorry, you cannot create appointments less than thirty minutes. Please try again."
        else:
            for app in Appointment.objects.all():
                if (date == app.date) and (doctor == app.doctor) and (
                            (old_appointment is not None and old_appointment.pk != app.pk) or old_appointment is None):
                    if start_time == app.start_time:
                        result[0] = False
                        result[1] = "Sorry, another appointment starts at that time. Please try again."
                    elif (start_time < app.start_time) and (end_time > app.start_time):
                        result[0] = False
                        result[1] = "Sorry, that time was taken. Please try again."
                    elif (start_time > app.start_time) and (start_time < app.end_time):
                        result[0] = False
                        result[1] = "Sorry, that time was taken. Please try again."
                    # check for if start_time is within ten minutes of another appointment's end_time
                    elif app.end_time < start_time and (datetime.datetime(100,1,1,start_time.hour, start_time.minute,00) - datetime.timedelta(minutes=10)).time() < app.end_time:
                        result[0] = False
                        result[1] = "Sorry, the appointment starts too soon to the end of another appointment. Please try again."
                    # check for if end_time is within ten minutes of another appointment's start_time
                    elif end_time < app.start_time and (datetime.datetime(100, 1, 1, end_time.hour, end_time.minute, 00) + datetime.timedelta(minutes=10)).time() > app.start_time:
                        result[0] = False
                        result[1] = "Sorry, the appointment ends too soon to the start of another appointment. Please try again."
                    # check for if doctor is in that hospital on that day
                    elif hospital != app.hospital:
                        result[0] = False
                        result[1] = "Sorry, the doctor is in a different hospital on that date. Please try again."
        return result

    def time_checker(self, start_time, end_time):
        """
        Validates appointment time
        :param start_time: starting time
        :param end_time: ending time
        :return: whether or not the time is valid
        """
        result = [True, "no message"]
        if(start_time < 8 or end_time < 8):
            result[0] = False
            result[1] = "Sorry, no appointments before 8 a.m."
        if (start_time > 18 or end_time > 18):
            result[0] = False
            result[1] = "Sorry, no appointments after 6 p.m."
        return result

HealthApps/models/Doctor.py
"""
file: Doctor.py
description: models for Doctors
"""

from django.db import models
from django.contrib.auth.models import User


class Doctor(models.Model):
    """
    Doctor model
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hospitals = models.ManyToManyField('HealthApps.Hospital', blank=True)
    max_patients = models.PositiveIntegerField()
    cur_patients = models.PositiveIntegerField(default=0)

    def __str__(self):
        """
        Tostring for Doctor
        :return: full name
        """
        return self.user.first_name + " " + self.user.last_name

    def get_type(self):
        """
        Returns user type
        :return: user type
        """
        return "doctor"

HealthApps/models/EMR_Entry.py
"""
file: EMR_Entry.py
description: models for EMR_Entrys
"""

from django.db import models


class EMR_Entry(models.Model):
    """
    EMR_Entry model
    """
    timestamp = models.DateTimeField(blank=True)
    patient = models.ForeignKey('HealthApps.Patient', on_delete=models.DO_NOTHING)

    test = models.ForeignKey('HealthApps.Test', on_delete=models.DO_NOTHING, blank=True, null=True)
    prescription = models.ForeignKey('HealthApps.Prescription', on_delete=models.DO_NOTHING, blank=True, null=True)

    description = models.CharField(max_length=255, blank=True)

    type = models.CharField(max_length=10)

    shown = models.BooleanField(default=False)

HealthApps/models/Hospital.py
"""
file: Hospital.py
description: models for Hospitals
"""

from django.db import models


class Hospital(models.Model):
    """
    Hospital model
    """
    name = models.CharField(max_length=30)
    admitted_patients = models.ManyToManyField('HealthApps.Patient', related_name='+', blank=True)

    def __str__(self):
        """
        Tostring for Hospital
        :return: name
        """
        return self.name

HealthApps/models/Hospital_Admin.py
"""
file: Hospital_Admin.py
description: models for Hospital_Admins
"""

from django.db import models
from django.contrib.auth.models import User


class Hospital_Admin(models.Model):
    """
    Hospital_Admin model
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hospital = models.ForeignKey('HealthApps.Hospital', on_delete=models.DO_NOTHING)

    def __str__(self):
        """
        Tostring for Hospital_Admin
        :return: full name
        """
        return self.user.first_name + " " + self.user.last_name

    def get_type(self):
        """
        Returns user type
        :return: user type
        """
        return "admin"

HealthApps/models/Patient.py
"""
file: Patient.py
description: models for Patients
"""

from django.db import models
from django.contrib.auth.models import User


class Patient(models.Model):
    """
    Patient model
    """
    insurance_number = models.CharField(max_length=13)
    hospital = models.ForeignKey('HealthApps.Hospital', on_delete=models.DO_NOTHING)
    admitted_to = models.ForeignKey('HealthApps.Hospital', on_delete=models.DO_NOTHING, related_name='+', null=True,
                                    blank=True)
    doctor = models.ForeignKey('HealthApps.Doctor', on_delete=models.DO_NOTHING)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    emergency_name = models.CharField(max_length=30)
    emergency_number = models.CharField(max_length=30)

    transfer_to = models.ForeignKey('HealthApps.Hospital', on_delete=models.DO_NOTHING, related_name='+', null=True,
                                    blank=True)
    height = models.FloatField(blank=True, null=True)  # Measured in inches | min: 6, max: 108
    weight = models.FloatField(blank=True, null=True)  # Measured in pounds | min: 0.5, max: 1500
    cholesterol = models.CharField(max_length=30, blank=True,
                                   null=True)  # Measured in mg/dL, X/X LDL/HDL | min: 90/25 max: 200/100
    pulse = models.PositiveIntegerField(blank=True, null=True)  # Measured in BPM | min: 25, max: 250
    temperature = models.FloatField(blank=True, null=True)  # Measured in Fahrenheit | min: 55, max: 120
    blood_pressure = models.CharField(max_length=30, blank=True,
                                      null=True)  # Measured in systolic/diastolic mm Hg | min: 100/60, max: 180/120

    blood_types = (('O', 'O'),
                   ('A', 'A'),
                   ('B', 'B'),
                   ('AB', 'AB'))
    blood_type = models.CharField(max_length=30, choices=blood_types)

    def __str__(self):
        """
        Tostring for patient
        :return: full name
        """
        return self.user.first_name + " " + self.user.last_name

    def get_type(self):
        """
        Returns user type
        :return: user type
        """
        return 'patient'

HealthApps/views/admin_control.py
"""
file: admin_control.py
description: provides administrator-only views
"""

from django.views.generic import CreateView

from ..views import CreateLogItem
from ..forms import HospitalForm
from ..models import Hospital
from ..utils import get_user_type


class CreateHospital(CreateView):
    """
    View for Hospital Creation
    """
    form_class = HospitalForm
    model = Hospital
    template_name = 'HealthApps/create_hospital.html'
    success_url = 'index.html'

    def get_context_data(self, **kwargs):
        """
        Updates form context data to include the request's user
        :return: updated context data
        """
        context = super(CreateView, self).get_context_data(**kwargs)
        context['user_type'] = get_user_type(self.request.user)
        return context

    def form_valid(self, form):
        """
        Overrides form_valid to create log item
        :param form: the specified form
        :return: the validity of the form
        """
        hospital = form.save(commit=False)
        CreateLogItem.li_hospital_create(self.request.user, hospital)
        return super(CreateHospital, self).form_valid(form)

HealthApps/views/cascade_select.py
"""
file: cascade_select.py
description: provides functions for cascading selects
"""

from django.http import JsonResponse
from ..models import Doctor


def hospital_to_doctor(request):
    """
    Gets all doctors associated with given hospital
    :param request: used to determine specified hospital
    :return: JSON response of doctors
    """
    hospital = request.GET.get('hospital')
    print(hospital)
    ret = []
    if hospital:
        for doctor in Doctor.objects.filter(hospitals__id__in=hospital):
            if doctor.cur_patients < doctor.max_patients:
                ret.append(dict(id=doctor.id, value=str(doctor)))
    return JsonResponse(ret, safe=False)

HealthApps/views/handle_csv.py
"""
file: handle_csv.py
description: views for csv
"""

from django.http import HttpResponseRedirect
from django.shortcuts import render
from ..utils import *


def handle_csv(request):
    """
    Handles the csv
    :param request:
    :return: renders the request
    """
    return render(request, 'HealthApps/handle_csv.html')


def import_csv(request, string):
    """
    Imports the csv
    :param request: the request
    :param string: the filename
    :return: redirects
    """
    import_data(string)
    return HttpResponseRedirect("/handleCSV")


def export_csv(request, string):
    """
    Exports the csv
    :param request: the request
    :param string: the filename
    :return: redirects
    """
    export_data(string)
    return HttpResponseRedirect("/handleCSV")

HealthApps/views/index.py
"""
file: index.py
description: view for index
"""

from django.http import HttpResponseRedirect
from django.shortcuts import render

from ..models import Hospital
from ..forms import LoginForm
from ..utils import get_user_type


def index(request):
    """
    Login on the index
    :param request:
    :return: renders the page
    """
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/profile')
    else:
        form = LoginForm()

    user_type = get_user_type(request.user)
    hospitals = []
    for hos in Hospital.objects.all():
        hospitals.append(hos)

    return render(request, 'HealthApps/index.html', dict(form=form, user_type=user_type, hospitals=hospitals))

HealthApps/templates/HealthApps/appointment_form.html
{% extends 'HealthApps/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">

    {% if header == "create" %}
       <h1>Create Appointment</h1>
    {% else %}
        <h1>Edit Appointment</h1>
    {% endif %}

        {% if user_type == "doctor" or user_type == "patient" or user_type == "nurse" %}
        <form enctype="multipart/form-data" action="" method="post" class="">{% csrf_token %}
            {% if user_type == "doctor"  or user_type == "nurse" %}
                <p>An appointment must be at least 30 minutes long.</p>
            {% endif %}
            <div class="col-md-5">
                <div class="form-group">
                    <br /><br /><label class="form-control-label">{{ form.date.label_tag }}</label><br />
                        <div class="col-xs-9">
                        <p>{{ form.date }}</p>
                        </div>
                        <p>{{ form.date.errors }}</p>
                </div>

                <div class="form-group">
                    <br /><br /><label class="form-control-label">{{ form.start_time.label_tag }}</label><br />
                        <p>Time is in 24 hr format.</p>
                        <div class="col-xs-9">
                        <p>{{ form.start_time }}</p>
                        </div>
                        <p>{{ form.start_time.errors }}</p>
                </div>

                <!-- these fields are hidden, but required-->
                {% if user_type == "patient" %}
                    {{ form.end_time.errors }}
                    {{ form.end_time.as_hidden }}
                    {{ form.patient.errors }}
                    {{ form.patient.as_hidden }}
                {% endif %}

                {% if user_type == "doctor" %}
                    <div class="form-group">
                        <br />
                        <br /><br /><label class="form-control-label">{{ form.end_time.label_tag }}</label><br />

                        <div class="col-xs-9">
                            <p>{{ form.end_time }}</p>
                        </div>
                        <p>{{ form.end_time.errors }}</p>
                </div>

                <div class="form-group">
                        <br /><br /><label class="form-control-label">{{ form.patient.label_tag }}</label><br />
                        <div class="col-xs-9">
                            <p>{{ form.patient }}</p>
                        </div>
                        <p>{{ form.patient.errors.as_text }}</p>
                </div>

                {% endif %}
                {% if user_type == "nurse" %}
                    <div class="form-group">
                        <br />
                        <br /><br /><label class="form-control-label">{{ form.end_time.label_tag }}</label><br />

                        <div class="col-xs-9">
                            <p>{{ form.end_time }}</p>
                        </div>
                        <p>{{ form.end_time.errors }}</p>
                </div>

                <div class="form-group">
                        <br /><br /><label class="form-control-label">{{ form.patient.label_tag }}</label><br />
                        <div class="col-xs-9">
                            <p>{{ form.patient }}</p>
                        </div>
                        <p>{{ form.patient.errors.as_text }}</p>
                </div>
                {% endif %}
                <br />
                <div class="form-group">
                        <br /><br /><label class="form-control-label" >{{ form.description.label_tag }}</label><br />
                        <div class="col-xs-9">

                            <p>{{ form.description }}</p>
                        </div>
                        <p>{{ form.description.errors }}</p>
                </div>
                </div>
                <br /><br />
                {% if messages %}
                    <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}

                {% if header == "create" %}
            <div class="col-xs-9">
                <input type="submit" value="Schedule Appointment" class="btn-primary"/><br /><br />
                <input type="submit" onclick="return confirm('You are about to exit without saving')" value="Exit Without Saving" name='goback' class="btn-default"/>
            </div>
                {% else %}
            <div class="col-xs-9">
                <input type="submit" value="Update Appointment" class="btn-success"/><br /><br />
            </div>
                <!--Nurse should not be able to see this button since they cannot cancel appointments-->
            <div class="col-xs-9">
                {% if user_type != "nurse" %}
                    <input type="submit" value="Cancel Appointment" name="cancel" class="btn-danger"/><br /><br />
                {% endif %}
                <input type="submit" onclick="return confirm('You are about to exit without saving')" value="Exit Without Saving" name='goback' class="btn-default"/>
            </div>
            {% endif %}




            </div>




            <script type="text/javascript">
                $(function () {
                    $('#id_date').datetimepicker({
                                format: 'YYYY-MM-DD'}
                    );
                });
            </script>
            <script type="text/javascript">
                $(function () {
                    $('#id_start_time').datetimepicker({
                                format: 'HH:mm'
                    }
                    );
                });
            </script>
            <script type="text/javascript">
                $(function () {
                    $('#id_end_time').datetimepicker({
                                format: 'HH:mm'
                    }
                    );
                });
            </script>
        <br />

      </form>
      {% endif %}
</div>
{% else %}
        Please Log in <a href="/login/">here</a>.
    {% endif %}
{% endblock %}

HealthApps/templates/HealthApps/block_off_form.html
{% extends 'HealthApps/base.html' %}
{% block content %}
<div class="container">
    <h1>Block Off Times</h1>
    {% if user.is_authenticated %}
        {% if user_type == "doctor" %}
        <form enctype="multipart/form-data" action="" method="post" class="">{% csrf_token %}
            {% if user_type == "doctor" %}
                <p>Please choose a time to block off</p>
            {% endif %}
            <div class="col-md-5">
                <div class="form-group">
                    <br /><br /><label class="form-control-label">{{ form.date.label_tag }}</label><br />
                        <div class="col-xs-9">
                        <p>{{ form.date }}</p>
                        </div>
                        <p>{{ form.date.errors }}</p>
                </div>

                <div class="form-group">
                    <br /><br /><label class="form-control-label">{{ form.start_time.label_tag }}</label><br />
                        <p>Time is in 24 hr format.</p>
                        <div class="col-xs-9">
                        <p>{{ form.start_time }}</p>
                        </div>
                        <p>{{ form.start_time.errors }}</p>
                </div>
                <div class="form-group">
                        <br />
                        <br /><br /><label class="form-control-label">{{ form.end_time.label_tag }}</label><br />

                        <div class="col-xs-9">
                            <p>{{ form.end_time }}</p>
                        </div>
                        <p>{{ form.end_time.errors }}</p>
                </div>
                {% if header != "update" %}
                    <div class="form-group">
                            <br />
                            <br /><br /><label class="form-control-label">{{ form.recurring.label_tag }} {{ form.recurring }}</label><br />
                            <p>{{ form.recurring.errors }}</p>
                    </div>
                    <div class="form-group">
                            <label class="form-control-label">{{ form.weeks.label_tag }}</label><br />

                            <div class="col-xs-9">
                                <p>{{ form.weeks }}</p>
                            </div>
                            <p>{{ form.weeks.errors }}</p>
                    </div>
                {% endif %}
                <br /><br /><br /><br />
                {% if header == "create" %}
                <input type="submit" value="Schedule Block Off" class="btn-primary"/>
                <input type="submit" onclick="return confirm('You are about to exit without saving')" value="Exit Without Saving" name='goback' class="btn-default"/>
            {% else %}
                <input type="submit" value="Update Block Off" class="btn-default"/>
                    <input type="submit" value="Cancel Block Off" name="cancel" class="btn-default"/>
                <input type="submit" onclick="return confirm('You are about to exit without saving')" value="Exit Without Saving" name='goback' class="btn-default"/>
            {% endif %}
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}

            </div>


            <script type="text/javascript">
                $(function () {
                    $('#id_date').datetimepicker({
                                format: 'YYYY-MM-DD'}
                    );
                });
            </script>
            <script type="text/javascript">
                $(function () {
                    $('#id_start_time').datetimepicker({
                                format: 'HH:mm'
                    }
                    );
                });
            </script>
            <script type="text/javascript">
                $(function () {
                    $('#id_end_time').datetimepicker({
                                format: 'HH:mm'
                    }
                    );
                });
            </script>
        <br />

      </form>
      {% endif %}
    {% else %}
        Please Log in <a href="/login/">here</a>.
    {% endif %}
</div>

{% endblock %}

HealthApps/templates/HealthApps/log_table.html
{% extends 'HealthApps/base.html' %}
{% block content %}
    <h1>Log Items</h1>
    Click on an entry to view details
    {% if request.user.is_superuser  or user_type == 'admin' %}
        <table class="table table-striped table-hover">
            <tr>
                <th>Timestamp</th>
                <th>Description</th>
            </tr>
            {% if log_items|length > 0 %}
                {% for log_item in log_items %}
                    <tr class="clickable-row" data-href="/logItem/{{ log_item.id }}" style="cursor: pointer; cursor: hand;">
                        <td>{{ log_item.timestamp }}</td>
                        <td>{{ log_item.description }}</td>
                    </tr>
                {% endfor %}
                <script>
                    jQuery(document).ready(function($) {
                        $(".clickable-row").click(function() {
                            window.document.location = $(this).data("href");
                        });
                    });
                </script>
            {% else %}
                <tr><td colspan="2">Nothing here yet!</td></tr>
            {% endif %}
        </table>
    {% else %}
        <div>Must be logged in as an admin to view logs.</div>
    {% endif %}
{% endblock %}

HealthApps/templates/HealthApps/medical_info.html
{% extends 'HealthApps/base.html' %}
{% block content %}
<div class="container">
    {{ form.non_field_errors }}
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <h2>Hospital</h2>
        {{ form.hospital }}
        {{ form.hospital.errors }}
        <h2>Doctor</h2>
        {{ form.doctor }}
        {{ form.doctor.errors }}
        <h2>Emergency Contact Name</h2>
        {{ form.emergency_name }}
        {{ form.emergency_name.errors }}
        <h2>Emergency Contact Number</h2>
        {{ form.emergency_number }}
        {{ form.emergency_number.errors }}
        <h2>Height</h2>
        {{ form.height }}
        {{ form.height.errors }}
        <h2>Weight</h2>
        {{ form.weight }}
        {{ form.weight.errors }}
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

HealthApps/templates/HealthApps/registration_options.html
{% extends 'HealthApps/base.html' %}
{% block content %}
{% if request.user.is_superuser or user_type == "admin" %}
<h1>Register a ...</h1>
{% else %}
<h1>Register as a...</h1>
{% endif %}
<div class="container">
    <a href="/createPatient" name="patient" class="btn btn-primary btn-lg">Patient</a>
    <a href="/createNurse" name="nurse" class="btn btn-primary btn-lg">Nurse</a>
    <a href="/createDoctor" name="doctor" class="btn btn-primary btn-lg">Doctor</a>
    {% if request.user.is_superuser %}
    <a href="/createAdmin" class="btn btn-primary btn-lg">Hospital Administrator</a>
    {% endif %}
    {% if request.user.is_superuser %}
    <a href="/createHospital" class="btn btn-primary btn-lg">Hospital</a>
    {% endif %}
</div>
{% endblock %}

HealthApps/templates/HealthApps/user_form.html
{% extends 'HealthApps/base.html' %}
{% block content %}
<div class="container">
<h1>Update Profile</h1>
    {{ form.non_field_errors }}
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <h2>Email</h2>
        {{ form.username}}
        {{ form.username.errors }}
        <h2>First Name</h2>
        {{ form.first_name }}
        {{ form.first_name.errors }}
        <h2>Last Name</h2>
        {{ form.last_name }}
        {{ form.last_name.errors }}
        <br>
        <input type="submit" value="Save" class="btn-default"/>
        <a href="/profile" class="btn-sm btn-default">Cancel</a>
  </form>
</div>
{% endblock %}